name: Get latest release from template
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    uses: ObsidianPublisher/actions/.github/workflows/update.yml@main
    with:
      AUTO_MERGE: false
      EXCLUDED-FILES: "overrides/hooks/on_page_markdown.py"
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
